FROM node:20-alpine
WORKDIR /app

# Archivo temporal para simular la aplicación mientras escribimos el código real
RUN echo "console.log('Omnipay API Gateway Bootstrapped!');" > main.js

CMD ["node", "main.js"]
